# Generated by Django 4.2.2 on 2025-11-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_appointment_appointment_date_appointment_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cost',
        ),
    ]
